# Generated by Django 6.0 on 2026-03-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_dog_description_dog_is_adoptable_dog_is_vaccinated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="is_adoption_post",
            field=models.BooleanField(default=False),
        ),
    ]
