# Generated by Django 6.0 on 2026-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_add_is_adoption_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="adoption_status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Booked", "Booked"),
                    ("Adopted", "Adopted"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
    ]
