# Generated by Django 6.0 on 2026-04-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_dog_adoption_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="adoption_status",
        ),
        migrations.AddField(
            model_name="dog",
            name="status",
            field=models.CharField(
                choices=[("Available", "Available"), ("Booked", "Booked")],
                default="Available",
                max_length=20,
            ),
        ),
    ]
