# Generated by Django 6.0 on 2026-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_remove_dog_adoption_status_dog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="status",
        ),
        migrations.AddField(
            model_name="dog",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
    ]
