# Generated by Django 6.0 on 2026-04-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0007_remove_dog_status_dog_is_booked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dog",
            name="is_booked",
        ),
    ]
