# Generated by Django 6.0 on 2026-04-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0008_remove_dog_is_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
