# Generated by Django 6.0.4 on 2026-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0009_dog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="dog_profiles/"
            ),
        ),
    ]
