from django.urls import path
from . import views

urlpatterns = [
    path('adoption/', views.adoption_listing_view, name='adoption'),
    path('contact/', views.contact_us_view, name='contact'),
    path('shop/', views.shop_view, name='shop'),
    path('cart/', views.cart_view, name='cart'),
    path('product/<int:product_id>/', views.product_details_view, name='product_details'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('dog-profile/', views.dog_profile_view, name='dogprofile'),
    path('dog-profile/<int:dog_id>/', views.dog_profile_view, name='dogprofile'),
    path('add-dog/', views.add_dog, name='add_dog'),
    path('edit-dog/<int:dog_id>/', views.edit_dog, name='edit_dog'),
    path('delete-dog/<int:dog_id>/', views.delete_dog, name='delete_dog'),
    path('add-vaccination/<int:dog_id>/', views.add_vaccination, name='add_vaccination'),
    path('edit-vaccination/<int:vaccination_id>/', views.edit_vaccination, name='edit_vaccination'),
    path('add-health-record/<int:dog_id>/', views.add_health_record, name='add_health_record'),
    path('delete-health-record/<int:record_id>/', views.delete_health_record, name='delete_health_record'),
    path('medicine-reminder/', views.medicine_reminder_view, name='medicinereminder'),
    path('vet-appointment/', views.vet_appointment_view, name='vetappointment'),
    path('reschedule-appointment/<int:appointment_id>/', views.reschedule_appointment, name='reschedule_appointment'),
    path('cancel-appointment/<int:appointment_id>/', views.cancel_appointment, name='cancel_appointment'),
    path('grooming-booking/', views.grooming_booking_view, name='groomingbooking'),
    path('reschedule-grooming/<int:booking_id>/', views.reschedule_grooming, name='reschedule_grooming'),
    path('cancel-grooming/<int:booking_id>/', views.cancel_grooming, name='cancel_grooming'),
    path('doctor-profile/<int:vet_id>/', views.doctor_profile_view, name='doctorprofile'),
    path('chat/<int:user_id>/', views.chat_room_view, name='chat'),
    path('chats/', views.chat_list_view, name='chat_list'),
]
