# Generated by Django 6.0 on 2026-03-16 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KhaltiPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment Payment"),
                            ("grooming", "Grooming Booking Payment"),
                            ("product", "Product Order Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pidx",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Payment Index",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("amount", models.BigIntegerField(help_text="Amount in paisa")),
                ("total_amount", models.BigIntegerField(blank=True, null=True)),
                ("fee", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("appointment_id", models.BigIntegerField(blank=True, null=True)),
                ("grooming_booking_id", models.BigIntegerField(blank=True, null=True)),
                ("order_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("payment_url", models.URLField(blank=True, null=True)),
                ("refunded", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="khalti_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("initiate", "Payment Initiation"),
                            ("lookup", "Payment Lookup"),
                            ("callback", "Payment Callback"),
                            ("refund", "Refund Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payment.khaltipayment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="khaltipayment",
            index=models.Index(fields=["pidx"], name="payment_kha_pidx_f74200_idx"),
        ),
        migrations.AddIndex(
            model_name="khaltipayment",
            index=models.Index(
                fields=["transaction_id"], name="payment_kha_transac_17aea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="khaltipayment",
            index=models.Index(
                fields=["user", "status"], name="payment_kha_user_id_d4f436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="khaltipayment",
            index=models.Index(
                fields=["payment_type", "status"], name="payment_kha_payment_cce5b9_idx"
            ),
        ),
    ]
