# Generated by Django 6.0 on 2026-03-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_appointment_appointment_fee_and_more"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="khaltipayment",
            name="payment_kha_pidx_f74200_idx",
        ),
        migrations.RemoveIndex(
            model_name="khaltipayment",
            name="payment_kha_transac_17aea1_idx",
        ),
        migrations.RemoveIndex(
            model_name="khaltipayment",
            name="payment_kha_user_id_d4f436_idx",
        ),
        migrations.RemoveIndex(
            model_name="khaltipayment",
            name="payment_kha_payment_cce5b9_idx",
        ),
        migrations.RemoveField(
            model_name="khaltipayment",
            name="user",
        ),
        migrations.DeleteModel(
            name="PaymentLog",
        ),
        migrations.DeleteModel(
            name="KhaltiPayment",
        ),
    ]
