# Generated by Django 6.0 on 2026-03-19 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroomingSalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=20)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "tags",
                    models.CharField(
                        help_text="Comma separated tags, e.g. Bath, Haircut, Nail Trim",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "db_table": "home_groomingsalon",
            },
        ),
        migrations.CreateModel(
            name="GroomingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.CharField(help_text="e.g. 45 min", max_length=50)),
                ("price", models.IntegerField(help_text="Price in Rs.")),
            ],
            options={
                "db_table": "home_groomingservice",
            },
        ),
        migrations.CreateModel(
            name="GroomingBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("booking_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Confirmed",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grooming_bookings",
                        to="pets.dog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grooming_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="grooming.groomingsalon",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="grooming.groomingservice",
                    ),
                ),
            ],
            options={
                "db_table": "home_groomingbooking",
            },
        ),
    ]
