# Generated by Django 6.0 on 2026-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0002_groomingbooking_amount_groomingbooking_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groomingbooking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
