# Generated by Django 6.0.4 on 2026-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_cover_picture_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover_picture",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="profiles/"
            ),
        ),
    ]
