# Generated by Django 6.0 on 2026-03-07 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_groomingsalon_groomingservice_groomingbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="age",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dog_profiles/"),
        ),
        migrations.AddField(
            model_name="dog",
            name="microchip_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="special_needs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="weight",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("record_type", models.CharField(max_length=100)),
                ("vet_name", models.CharField(max_length=100)),
                ("notes", models.TextField()),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="home.dog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("last_given", models.DateField()),
                ("next_due", models.DateField()),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="home.dog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date_administered", models.DateField()),
                ("next_due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Current", "Current"), ("Due Soon", "Due Soon")],
                        default="Current",
                        max_length=20,
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="home.dog",
                    ),
                ),
            ],
        ),
    ]
