# Generated by Django 6.0 on 2026-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_dog_age_dog_color_dog_date_of_birth_dog_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="achievements",
            field=models.TextField(
                blank=True, help_text="Comma separated achievements", null=True
            ),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="consultation_fee",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="education",
            field=models.TextField(
                blank=True, help_text="Comma separated education details", null=True
            ),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="experience_years",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="expertise",
            field=models.TextField(
                blank=True, help_text="Comma separated areas of expertise", null=True
            ),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="vets/"),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="is_emergency_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="languages",
            field=models.CharField(default="Nepali, English", max_length=200),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="specialty",
            field=models.CharField(
                default="General Veterinary Medicine", max_length=100
            ),
        ),
    ]
