# Generated by Django 6.0 on 2026-03-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_product_order"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_fee",
            field=models.IntegerField(default=500, help_text="Fee in Rs."),
        ),
        migrations.AddField(
            model_name="appointment",
            name="khalti_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment",
                to="payment.khaltipayment",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Payment Pending"),
                    ("paid", "Payment Paid"),
                    ("failed", "Payment Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="groomingbooking",
            name="khalti_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grooming_booking",
                to="payment.khaltipayment",
            ),
        ),
        migrations.AddField(
            model_name="groomingbooking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Payment Pending"),
                    ("paid", "Payment Paid"),
                    ("failed", "Payment Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
