# Generated by Django 6.0 on 2026-03-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_appointment_appointment_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_fee",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="khalti_payment",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="groomingbooking",
            name="khalti_payment",
        ),
        migrations.RemoveField(
            model_name="groomingbooking",
            name="payment_status",
        ),
    ]
