# Generated by Django 6.0 on 2026-03-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_product_description_product_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
