# Generated by Django 6.0.4 on 2026-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_productreview_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="products/"
            ),
        ),
    ]
