# Generated by Django 6.0 on 2026-03-19 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "home_clinic",
            },
        ),
        migrations.CreateModel(
            name="Veterinarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "specialty",
                    models.CharField(
                        default="General Veterinary Medicine", max_length=100
                    ),
                ),
                ("experience_years", models.IntegerField(default=5)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "expertise",
                    models.TextField(
                        blank=True,
                        help_text="Comma separated areas of expertise",
                        null=True,
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True,
                        help_text="Comma separated education details",
                        null=True,
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Comma separated achievements", null=True
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("consultation_fee", models.IntegerField(default=1000)),
                (
                    "languages",
                    models.CharField(default="Nepali, English", max_length=200),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="vets/")),
                ("is_emergency_available", models.BooleanField(default=False)),
                ("initial", models.CharField(blank=True, max_length=1)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinarians",
                        to="veterinary.clinic",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vet_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "home_veterinarian",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Regular Checkup", "Regular Checkup"),
                            ("Vaccination", "Vaccination"),
                            ("Emergency", "Emergency"),
                            ("Follow-up", "Follow-up"),
                            ("Consultation", "Consultation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Confirmed",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="pets.dog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="veterinary.veterinarian",
                    ),
                ),
            ],
            options={
                "db_table": "home_appointment",
            },
        ),
    ]
