# Generated by Django 6.0 on 2026-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="amount",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="pidx",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
