# Generated by Django 6.0 on 2026-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "veterinary",
            "0002_appointment_amount_appointment_paid_appointment_pidx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="available_time",
            field=models.CharField(
                default="Mon - Fri, 09:00 AM - 05:00 PM", max_length=200
            ),
        ),
    ]
