# Generated by Django 6.0 on 2026-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0003_veterinarian_available_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinarian",
            name="emergency_fee",
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="followup_fee",
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="regular_checkup_fee",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="veterinarian",
            name="vaccination_fee",
            field=models.IntegerField(default=1500),
        ),
    ]
