# Generated by Django 6.0 on 2026-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "veterinary",
            "0004_veterinarian_emergency_fee_veterinarian_followup_fee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
