# Generated by Django 6.0.4 on 2026-04-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0005_appointment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="created_at",
        ),
    ]
